# WEB SCRAPING – ASSIGNMENT 4

Q7 Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through cod

In [1]:
#Import necessory libraries
import selenium
from bs4 import BeautifulSoup
import requests
import pandas as pd
import time
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException

In [56]:
# loading Chrome webdriver
driver = webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")

C:\Users\hp\AppData\Local\Temp/ipykernel_14676/2288193282.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")

In [57]:
# Opening Desired Webpage
driver.get('https://www.naukri.com/')
driver.maximize_window()        #maximizing the webpage

In [58]:
# clicking on the recruiters option from the search panel.
driver.find_element_by_xpath('//div[@id="root"]/div/div/div/ul/li/a/div').click()

C:\Users\hp\AppData\Local\Temp/ipykernel_14676/2631869637.py:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_xpath('//div[@id="root"]/div/div/div/ul/li/a/div').click()

In [59]:
# specifying the url to be scraped
url='https://www.naukri.com/hr-recruiters-consultants'

In [60]:
driver.get(url)

In [61]:
# Entering Data Scientist in Skills,Designations,companies field.
url=driver.find_element_by_xpath('//*[@id="skill"]/div[1]/div[2]/input').send_keys('Data Science')

C:\Users\hp\AppData\Local\Temp/ipykernel_14676/427796251.py:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  url=driver.find_element_by_xpath('//*[@id="skill"]/div[1]/div[2]/input').send_keys('Data Science')

In [62]:
# Creating empty lists for the scraped details from the webpage.

naukri={}
naukri['Name']=[]
naukri['Desgination']=[]
naukri['Company']=[]
naukri['Skills']=[]

# extracting name of recruiters from webpage by xpath

try:
    for i in driver.find_elements_by_xpath('//span[@class="fl ellipsis"]'):
        naukri['Name'].append(i.text)
except NoSuchElementExceptions:
    naukri['Name'].append('--')
    
# extracting Desgination of person from webapge by xpath

try:
    for i in driver.find_elements_by_xpath('//span[@class="ellipsis clr"]'):
        naukri['Desgination'].append(i.text)
except NoSuchElementExceptions:
    naukri['Desgination'].append('--')
    
# extracting Company name from webpage by xpath

try:
    for i in driver.find_elements_by_xpath('//div[@class="vcard"]/p/a[2]'):
        naukri['Company'].append(i.text)
except NoSuchElementExceptions:
    naukri['Company'].append('--')
    
    
# extracting Skills they hire for from webpape by xpath

try:
    for i in driver.find_elements_by_xpath('//div[@class="hireSec"]'):
        naukri['Skills'].append(i.text)
except NoSuchElementExceptions:
    naukri['Skills'].append('--')

C:\Users\hp\AppData\Local\Temp/ipykernel_14676/558491396.py:12: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath('//span[@class="fl ellipsis"]'):
C:\Users\hp\AppData\Local\Temp/ipykernel_14676/558491396.py:20: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath('//span[@class="ellipsis clr"]'):
C:\Users\hp\AppData\Local\Temp/ipykernel_14676/558491396.py:28: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath('//div[@class="vcard"]/p/a[2]'):
C:\Users\hp\AppData\Local\Temp/ipykernel_14676/558491396.py:37: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath('//div[@class="hireSec"]'):

In [63]:
print(len(naukri['Name']),len(naukri['Desgination']),len(naukri['Company']),len(naukri['Skills']))

18 18 13 8

In [72]:
Desgination=naukri['Desgination'][0:8] 
Name=naukri['Name'][0:8]
Company=naukri['Company'][0:8]
Skills=naukri['Skills']

In [65]:
url=[]
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p//a[1]"):
    url.append(i.get_attribute('href'))
url

C:\Users\hp\AppData\Local\Temp/ipykernel_14676/4290413635.py:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//div[@class='vcard']//p//a[1]"):

['https://www.naukri.com/recruiters/santhoshkumaresan?xz=1_0_12&xid=164216645541641100&xp=1',
 'https://www.naukri.com/recruiters/surendrar-3720714?xz=1_0_12&xid=164216645541641100&xp=2',
 'https://www.naukri.com/recruiters/gauribhosle?xz=1_0_12&xid=164216645541641100&xp=3',
 'https://www.naukri.com/recruiters/sanghvi-3518304?xz=1_0_12&xid=164216645541641100&xp=4',
 'https://www.naukri.com/recruiters/rohitkhandelwal-3755864?xz=1_0_12&xid=164216645541641100&xp=5',
 'https://www.naukri.com/recruiters/nehapandey-3587618?xz=1_0_12&xid=164216645541641100&xp=6',
 'https://www.naukri.com/recruiters/vinitaraut-3601272?xz=1_0_12&xid=164216645541641100&xp=7',
 'https://www.naukri.com/recruiters/codeflies-2507804?xz=1_0_12&xid=164216645541641100&xp=8',
 'https://www.naukri.com/recruiters/snehal-1705770?xz=1_0_12',
 'https://www.naukri.com/recruiters/Integra-Ventures?xz=1_0_12',
 'https://www.naukri.com/recruiters/codeflies-2507804?xz=1_0_12',
 'https://www.naukri.com/recruiters/kalyandadepogu?xz=1_0_12',
 'https://www.naukri.com/recruiters/hrteronext?xz=1_0_12']

In [66]:
# extracting location
naukri['Location']=[]
for i in url:
    driver.get(i)
    try:
        naukri['Location'].append(driver.find_element_by_xpath('//div[@class="rFrame fl infoWrapper"]//div[5]/a').text)
    except NoSuchElemetnException:
        naukri['Location'].append("--")

C:\Users\hp\AppData\Local\Temp/ipykernel_14676/3495133657.py:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  naukri['Location'].append(driver.find_element_by_xpath('//div[@class="rFrame fl infoWrapper"]//div[5]/a').text)

In [71]:
Location=naukri['Location'][0:8]

In [73]:
naukri_df = pd.DataFrame({ 'Location':Location,'Desgination': Desgination,
                      'Name': Name,
                      'Company': Company,'Skills':Skills})
naukri_df

,Location,Desgination,Name,Company,Skills
0,Chennai,Associate Manager Human Resources,Santhosh Kumar,Maveric Systems,"It Recruitment, Campus Recruitment, Campus Hir..."
1,Hyderabad / Secunderabad,Company Recruiter,Surendra R,DSR Design & Engineering Solutions,"Design Engineering, AutoCAD, Solid Works"
2,Mumbai,Human Resources,Gauri Bhosle,TCRC,"Operation Executive, Jr. Chemist/ Chemist, Aud..."
3,Ahmedabad,Company Recruiter,Sanghvi,Primacy Systems Pvt Ltd,"Marketing, Sales, Plastic, Aluminium, Metal, S..."
4,Jaipur,Company Recruiter,Rohit Khandelwal,PADHAI HELP PRIVATE LIMITED,Marketing
5,Gurgaon,Company Recruiter,Neha Pandey,Ingenious E-Brain Solutions Private Limited,"B.tech, Operations, Business Development, Busi..."
6,Pune,Company Recruiter,Vinita Raut,Xpansion HR Solutions Private Limited,"Bde, Accounting, Education Counseling, Sales, ..."
7,Noida,Human Resources,CodeFlies,CodeFlies,"Email Marketing, Communication, Online Lead Ge..."

Q8Scrape the details of Highest selling novels.

Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
    
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [74]:
# loading Chrome webdriver
driver = webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")

C:\Users\hp\AppData\Local\Temp/ipykernel_14676/2288193282.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")

In [75]:
#Opening desried webpage
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')
driver.maximize_window()

In [76]:
book={}
book['Book Name']=[]
book['Author']=[]
book['Volumes Sold']=[]
book['Publisher']=[]
book['Genre']=[]

# extracting book name

for i in range(0,100):
    try:
        book['Book Name'].append(driver.find_element_by_xpath('//td[@id="table-cell-10943-{}-1"]'.format(i)).text)
    except NoSuchElementException:
        book['Book Name'].append['--']
        
# extracting author name

    try:
        book['Author'].append(driver.find_element_by_xpath('//td[@id="table-cell-10943-{}-2"]'.format(i)).text)
    except NoSuchElementException:
        book['Author'].append['--']
        
# extracting Volumes sold

    try:
        book['Volumes Sold'].append(driver.find_element_by_xpath('//td[@id="table-cell-10943-{}-3"]'.format(i)).text)
    except NoSuchElementException:
        book['Volumes Sold'].append['--']
        
# extracting Publisher

    try:
        book['Publisher'].append(driver.find_element_by_xpath('//td[@id="table-cell-10943-{}-4"]'.format(i)).text)
    except NoSuchElementException:
        book['Publisher'].append['--']
        
# extracting Genre

    try:
        book['Genre'].append(driver.find_element_by_xpath('//td[@id="table-cell-10943-{}-5"]'.format(i)).text)
    except NoSuchElementException:
        book['Genre'].append['--']

C:\Users\hp\AppData\Local\Temp/ipykernel_14676/1328050518.py:12: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  book['Book Name'].append(driver.find_element_by_xpath('//td[@id="table-cell-10943-{}-1"]'.format(i)).text)
C:\Users\hp\AppData\Local\Temp/ipykernel_14676/1328050518.py:19: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  book['Author'].append(driver.find_element_by_xpath('//td[@id="table-cell-10943-{}-2"]'.format(i)).text)
C:\Users\hp\AppData\Local\Temp/ipykernel_14676/1328050518.py:26: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  book['Volumes Sold'].append(driver.find_element_by_xpath('//td[@id="table-cell-10943-{}-3"]'.format(i)).text)
C:\Users\hp\AppData\Local\Temp/ipykernel_14676/1328050518.py:33: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  book['Publisher'].append(driver.find_element_by_xpath('//td[@id="table-cell-10943-{}-4"]'.format(i)).text)
C:\Users\hp\AppData\Local\Temp/ipykernel_14676/1328050518.py:40: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  book['Genre'].append(driver.find_element_by_xpath('//td[@id="table-cell-10943-{}-5"]'.format(i)).text)

In [77]:
novel=pd.DataFrame.from_dict(book)
novel

,Book Name,Author,Volumes Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

Q9Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
    
You have to find the following details:
    
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [79]:
# loading Chrome webdriver
driver = webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")

C:\Users\hp\AppData\Local\Temp/ipykernel_14676/2288193282.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")

In [80]:
#Opening desried webpage
driver.get('https://www.imdb.com/list/ls095964455/')
driver.maximize_window()

In [81]:
tv={}
tv['Name']=[]
tv['Year span']=[]
tv['Genre']=[]
tv['Runtime']=[]
tv['Ratings']=[]
tv['Votes']=[]

# extracting Name

try:
    for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
        tv['Name'].append(i.text)
except NoSuchElementExceptions:
    tv['Name'].append('--')
    
# extracting Year span

try:
    for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]"):
        tv['Year span'].append(i.text)
except NoSuchElementExceptions:
    tv['Year span'].append('--')
    
# extracting Genre

try:
    for i in driver.find_elements_by_xpath("//span[@class='genre']"):
        tv['Genre'].append(i.text)
except NoSuchElementExceptions:
    tv['Genre'].append('--')
    
# extracting Runtime

try:
    for i in driver.find_elements_by_xpath("//span[@class='runtime']"):
        tv['Runtime'].append(i.text)
except NoSuchElementExceptions:
    tv['Runtime'].append('--')
    
# extracting Ratings

try:
    for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']//span[2]"):
        tv['Ratings'].append(i.text)
except NoSuchElementExceptions:
    tv['Ratings'].append('--')
    
# extracting Votes

try:
    for i in driver.find_elements_by_xpath("//p[@class='text-muted text-small'][3]/span[2]"):
        tv['Votes'].append(i.text)
except NoSuchElementExceptions:
    tv['Votes'].append('--')

C:\Users\hp\AppData\Local\Temp/ipykernel_14676/1784326670.py:12: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
C:\Users\hp\AppData\Local\Temp/ipykernel_14676/1784326670.py:20: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]"):
C:\Users\hp\AppData\Local\Temp/ipykernel_14676/1784326670.py:28: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//span[@class='genre']"):
C:\Users\hp\AppData\Local\Temp/ipykernel_14676/1784326670.py:36: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//span[@class='runtime']"):
C:\Users\hp\AppData\Local\Temp/ipykernel_14676/1784326670.py:44: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']//span[2]"):
C:\Users\hp\AppData\Local\Temp/ipykernel_14676/1784326670.py:52: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//p[@class='text-muted text-small'][3]/span[2]"):

In [82]:
shows=pd.DataFrame.from_dict(tv)
shows

,Name,Year span,Genre,Runtime,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,930,698"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"951,549"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"922,223"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"276,329"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"236,575"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"47,182"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"57,976"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"183,054"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"38,336"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"218,028"

Q10Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
    
You have to find the following details:
A) Dataset name

B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code

In [3]:
# loading Chrome webdriver
driver = webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/2288193282.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")

In [4]:
driver.get('https://archive.ics.uci.edu/ml/index.php')
driver.maximize_window()

In [5]:
# Clicking on the view all data sets.
driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/span/b/a').click()

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/3572531621.py:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/span/b/a').click()

In [12]:
#Creating empty lists for the information of UCI Datasets.
dataset={}
dataset['name']=[]
dataset['datatype']=[]
dataset['task']=[]
dataset['attributetype']=[]
dataset['no_of_instances']=[]
dataset['no_of_attributes']=[]
dataset['year']=[]

# extracting dataset name

try:
    for i in driver.find_elements_by_xpath("//p[@class='normal']//b/a"):
        dataset['name'].append(i.text)
except NoSuchElementException:
    dataset['name'].append('--')

for i in range (2,587):
    
# extracting data type

    try:
        dataset['datatype'].append(driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{}]/td[2]/p'.format(i)).text)
    except NoSuchElementException:
        dataset['datatype'].append('--')
        
#extracting task

    try:
        dataset['task'].append(driver.find_element_by_xpath('//table[@border="1"]//tr[{}]//td[3]'.format(i)).text)
    except NoSuchElementException:
        dataset['task'].append('--')
        
#extracting attribute types

    try:
        dataset['attributetype'].append(driver.find_element_by_xpath('//table[@border="1"]//tr[{}]//td[4]'.format(i)).text)
    except NoSuchElementException:
        dataset['attributetype'].append('--')
        
#extracting Number of instances

    try:
        dataset['no_of_instances'].append(driver.find_element_by_xpath('//table[@border="1"]//tr[{}]//td[5]'.format(i)).text)
    except NoSuchElementException:
        dataset['no_of_instances'].append('--')
        
#extracting Number of attributes

    try:
        dataset['no_of_attributes'].append(driver.find_element_by_xpath('//table[@border="1"]//tr[{}]//td[6]'.format(i)).text)
    except NoSuchElementException:
        dataset['no_of_attributes'].append('--')
        
#extracting Year

    try:
        dataset['year'].append(driver.find_element_by_xpath('//table[@border="1"]//tr[{}]//td[7]'.format(i)).text)
    except NoSuchElementException:
        dataset['year'].append('--')

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1641124110.py:14: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//p[@class='normal']//b/a"):
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1641124110.py:24: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  dataset['datatype'].append(driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{}]/td[2]/p'.format(i)).text)
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1641124110.py:31: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  dataset['task'].append(driver.find_element_by_xpath('//table[@border="1"]//tr[{}]//td[3]'.format(i)).text)
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1641124110.py:38: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  dataset['attributetype'].append(driver.find_element_by_xpath('//table[@border="1"]//tr[{}]//td[4]'.format(i)).text)
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1641124110.py:45: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  dataset['no_of_instances'].append(driver.find_element_by_xpath('//table[@border="1"]//tr[{}]//td[5]'.format(i)).text)
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1641124110.py:52: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  dataset['no_of_attributes'].append(driver.find_element_by_xpath('//table[@border="1"]//tr[{}]//td[6]'.format(i)).text)
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1641124110.py:59: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  dataset['year'].append(driver.find_element_by_xpath('//table[@border="1"]//tr[{}]//td[7]'.format(i)).text)

In [18]:
print(len(dataset['name']),len(dataset['datatype']),len(dataset['task']),len(dataset['attributetype']),len(dataset['no_of_instances']),len(dataset['no_of_attributes']),len(dataset['year']))

622 585 585 585 585 585 585

In [19]:
dataset['name']=dataset['name'][0:585]
datasets=pd.DataFrame.from_dict(dataset)
datasets

,name,datatype,task,attributetype,no_of_instances,no_of_attributes,year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
580,Wisesight Sentiment Corpus,"Multivariate, Text",Classification,,26737,4,2020
581,AI4I 2020 Predictive Maintenance Dataset,"Multivariate, Time-Series","Classification, Regression, Causal-Discovery",Real,10000,14,2020
582,Dry Bean Dataset,Multivariate,Classification,"Integer, Real",13611,17,2020
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020

Q1Scrape the details of most viewed videos on YouTube from Wikipedia. Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details:

A) Rank B) Name C) Artist D) Upload date E) Views

In [20]:
#Activating the chrome browser

driver=webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe") 
time.sleep(4)
#Getting youtube wikipedia page
url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)
time.sleep(6)

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1563685715.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")

In [21]:
# Creating empty list for scaping the data

Rank = []
Name = []
Artist = []
Upload_Date = []
Views = []

In [22]:
# Scraping Rank of the videos
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")
    
# Scraping Name of the videos
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]"):
        Name.append(i.text)
except NoSuchElementException:
    Name.append("_")
    
# Scraping Artist of the video
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]"):
        Artist.append(i.text)
except NoSuchElementException:
    Artist.append("_")

# Scraping Uploaded date of the video
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]"):
        Upload_Date.append(i.text)
except NoSuchElementException:
    Upload_Date.append("_")
    
# Scraping Views of videos
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]"):
        Views.append(i.text)
except NoSuchElementException:
    Views.append("_")
    
# Creating DataFrame from scraped data
Wiki = pd.DataFrame({})
Wiki['Rank']=Rank
Wiki['Name']=Name
Wiki['Artist']=Artist
Wiki['Upload Date']=Upload_Date
Wiki['Views']=Views

# Removing stray numbers from Name column
Wiki.Name = Wiki.Name.apply(lambda x:x[:-4].strip('"'))
Wiki

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/2584960682.py:3: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]"):
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/2584960682.py:10: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]"):
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/2584960682.py:17: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]"):
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/2584960682.py:24: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]"):
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/2584960682.py:31: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]"):

,Rank,Name,Artist,Upload Date,Views
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,10.00,"June 17, 2016"
1,2.,Despacito,Luis Fonsi,7.70,"January 12, 2017"
2,3.,Johny Johny Yes Papa,LooLoo Kids,6.10,"October 8, 2016"
3,4.,Shape of You,Ed Sheeran,5.58,"January 30, 2017"
4,5.,See You Again,Wiz Khalifa,5.38,"April 6, 2015"
5,6.,Bath Song,Cocomelon – Nursery Rhymes,4.86,"May 2, 2018"
6,7.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,4.55,"February 27, 2018"
7,8.,Masha and the Bear – Recipe for Disaster,Get Movies,4.48,"January 31, 2012"
8,9.,Uptown Funk,Mark Ronson,4.42,"November 19, 2014"
9,10.,Phonics Song with Two Words,ChuChu TV,4.41,"March 6, 2014"
10,11.,Gangnam Style,Psy,4.31,"July 15, 2012"
11,12.,Dame Tu Cosita,El Chombo,3.80,"April 5, 2018"
12,13.,Sugar,Maroon 5,3.62,"January 14, 2015"
13,14.,Sorry,Justin Bieber,3.50,"October 22, 2015"
14,15.,Roar,Katy Perry,3.50,"September 5, 2013"
15,16.,Wheels on the Bus,Cocomelon – Nursery Rhymes,3.50,"May 24, 2018"
16,17.,Counting Stars,OneRepublic,3.48,"May 31, 2013"
17,18.,Thinking Out Loud,Ed Sheeran,3.39,"October 7, 2014"
18,19.,Girls Like You,Maroon 5,3.21,"May 31, 2018"
19,20.,Faded,Alan Walker,3.21,"December 3, 2015"
20,21.,Dark Horse,Katy Perry,3.21,"February 20, 2014"
21,22.,Axel F,Crazy Frog,3.17,"June 16, 2009"
22,23.,Let Her Go,Passenger,3.15,"July 25, 2012"
23,24.,Bailando,Enrique Iglesias,3.15,"April 11, 2014"
24,25.,Lean On,Major Lazer,3.15,"March 22, 2015"
25,26.,Shake It Off,Taylor Swift,3.13,"August 18, 2014"
26,27.,Baa Baa Black Sheep,Cocomelon – Nursery Rhymes,3.07,"June 25, 2018"
27,28.,Perfect,Ed Sheeran,3.06,"November 9, 2017"
28,29.,Waka Waka (This Time for Africa),Shakira,3.03,"June 4, 2010"
29,30.,Mi Gente,J Balvin,3.03,"June 29, 2017"

 Q4Scrape the details of State-wise GDP of India from statisticstime.com.

Url = http://statisticstimes.com/

You have to find following details: A) Rank B) State C) GSDP D) GSDP E) Share F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

In [23]:
# loading Chrome webdriver
driver = webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")
driver.get('http://statisticstimes.com/')
driver.maximize_window()

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1574575967.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")

In [24]:
#searching for the xpath for economy.
driver.find_element_by_xpath('//div[@class="dropdown"][2]//button').click()

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1118597660.py:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_xpath('//div[@class="dropdown"][2]//button').click()

In [25]:
#searching for the xpath for India in economy.
driver.find_element_by_xpath('//div[@class="dropdown-content"]/a[3]').click()

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/2404538852.py:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_xpath('//div[@class="dropdown-content"]/a[3]').click()

In [27]:
# searching on to the page of GDp of Indian States.
driver.find_element_by_xpath("//ul[@style='list-style-type:none;margin-left:20px;']//li/a").click()

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/3504551078.py:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_xpath("//ul[@style='list-style-type:none;margin-left:20px;']//li/a").click()

In [28]:
# Creating empty list for loading scraped data.

gdp={}
gdp['Rank']=[]
gdp['State']=[]
gdp['GSDP(19-20)']=[]
gdp['GSDP(18-19)']=[]
gdp['Share']=[]
gdp['GDP($billion)']=[]

for i in range(1,34):
    
#extracting Rank

    try:
        gdp['Rank'].append(driver.find_element_by_xpath("//table[@id='table_id']//tr[{}]/td[1]".format(i)).text)
    except NoSuchElementException:
        gdp['Rank'].append('--')
        
#extracting State

    try:
        gdp['State'].append(driver.find_element_by_xpath("//table[@id='table_id']//tr[{}]/td[2]".format(i)).text)
    except NoSuchElementException:
        gdp['State'].append('--')
        
#extracting GSDP(19-20)

    try:
        gdp['GSDP(19-20)'].append(driver.find_element_by_xpath("//table[@id='table_id']//tr[{}]/td[3]".format(i)).text)
    except NoSuchElementException:
        gdp['GSDP(19-20)'].append('--')
        
#extracting GSDP(18-19)

    try:
        gdp['GSDP(18-19)'].append(driver.find_element_by_xpath("//table[@id='table_id']//tr[{}]/td[4]".format(i)).text)
    except NoSuchElementException:
        gdp['GSDP(18-19)'].append('--')
        
#extracting Share

    try:
        gdp['Share'].append(driver.find_element_by_xpath("//table[@id='table_id']//tr[{}]/td[5]".format(i)).text)
    except NoSuchElementException:
        gdp['Share'].append('--')
        
#extracting GDP($billion)

    try:
        gdp['GDP($billion)'].append(driver.find_element_by_xpath("//table[@id='table_id']//tr[{}]/td[6]".format(i)).text)
    except NoSuchElementException:
        gdp['GDP($billion)'].append('--')

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/3302695043.py:16: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  gdp['Rank'].append(driver.find_element_by_xpath("//table[@id='table_id']//tr[{}]/td[1]".format(i)).text)
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/3302695043.py:23: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  gdp['State'].append(driver.find_element_by_xpath("//table[@id='table_id']//tr[{}]/td[2]".format(i)).text)
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/3302695043.py:30: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  gdp['GSDP(19-20)'].append(driver.find_element_by_xpath("//table[@id='table_id']//tr[{}]/td[3]".format(i)).text)
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/3302695043.py:37: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  gdp['GSDP(18-19)'].append(driver.find_element_by_xpath("//table[@id='table_id']//tr[{}]/td[4]".format(i)).text)
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/3302695043.py:44: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  gdp['Share'].append(driver.find_element_by_xpath("//table[@id='table_id']//tr[{}]/td[5]".format(i)).text)
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/3302695043.py:51: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  gdp['GDP($billion)'].append(driver.find_element_by_xpath("//table[@id='table_id']//tr[{}]/td[6]".format(i)).text)

In [29]:
GDP=pd.DataFrame.from_dict(gdp)
GDP

,Rank,State,GSDP(19-20),GSDP(18-19),Share,GDP($billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

@5Scrape the details of trending repositories on Github.com.

Url = https://github.com/

You have to find the following details: A) Repository title B) Repository description C) Contributors count D) Language used

In [30]:
# loading Chrome webdriver
driver = webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/2288193282.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")

In [35]:
# webpage opening
driver.get("https://github.com/")

time.sleep(5)

In [37]:
#clicking explore tab
expl_tag = driver.find_element_by_xpath("//div[1]/header/div/div[2]/nav/ul/li[4]/details/summary")
expl_tag.click()
    
time.sleep(2)
#trnd
trend_tag = driver.find_element_by_xpath("//ul[@class='list-style-none f5 pb-1']/li[2]/a")
trend_tag = driver.find_element_by_xpath("//div[@class='d-flex flex-wrap flex-items-center flex-justify-center flex-md-justify-start text-center text-md-left']/a[3]")
trend_tag.click()

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/3096782533.py:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  expl_tag = driver.find_element_by_xpath("//div[1]/header/div/div[2]/nav/ul/li[4]/details/summary")
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/3096782533.py:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  trend_tag = driver.find_element_by_xpath("//ul[@class='list-style-none f5 pb-1']/li[2]/a")
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/3096782533.py:8: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  trend_tag = driver.find_element_by_xpath("//div[@class='d-flex flex-wrap flex-items-center flex-justify-center flex-md-justify-start text-center text-md-left']/a[3]")

In [38]:
# vreating variable to store the data
title = []
desc = []
contri = []
lang = []
url = []

#scraping title
for h in driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a"):
    title.append(h.text[h.text.find("/")+1:])

# sraping language used
loop = range(1,26)
for i in loop:
    try:
        a = driver.find_element_by_xpath('//*[@id="js-pjax-container"]/div[3]/div/div[2]/article['+str(i)+']/div[2]/span[1]/span[2]')
        lang.append(a.text)
    except NoSuchElementException:
        lang.append('-')

# scraping contribution count
for j in driver.find_elements_by_xpath("//div[@class='f6 color-fg-muted mt-2']/a[2]"):
    contri.append(j.text)
    
# scraping title and url
for k in driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a"):
    url.append(k.get_attribute('href'))
# scraping title and language
for l in driver.find_elements_by_xpath("//div[@class='f6 color-fg-muted mt-2']/span/span[2]"):
    lang.append(l.text) 
# scraping title and  Repository description    
for m in driver.find_elements_by_xpath("//p[@class='col-9 color-fg-muted my-1 pr-4']"):
    desc.append(m.text)

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1016353755.py:9: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for h in driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a"):
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1016353755.py:16: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  a = driver.find_element_by_xpath('//*[@id="js-pjax-container"]/div[3]/div/div[2]/article['+str(i)+']/div[2]/span[1]/span[2]')
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1016353755.py:22: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for j in driver.find_elements_by_xpath("//div[@class='f6 color-fg-muted mt-2']/a[2]"):
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1016353755.py:26: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for k in driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a"):
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1016353755.py:29: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for l in driver.find_elements_by_xpath("//div[@class='f6 color-fg-muted mt-2']/span/span[2]"):
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1016353755.py:32: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for m in driver.find_elements_by_xpath("//p[@class='col-9 color-fg-muted my-1 pr-4']"):

In [41]:
print(len(url),len(contri),len(title),len(lang),len(desc))
lang=lang[0:22]
title=title[0:22]
contri=contri[0:22]
url=url[0:22]

24 24 24 24 22

In [42]:
github = pd.DataFrame({ 'URL':url,'Repository title': title,
                      'Contributord count': contri,
                      'Language Used': lang,'Description':desc})
github

,URL,Repository title,Contributord count,Language Used,Description
0,https://github.com/v4d1/SpoofThatMail,SpoofThatMail,24,Shell,Bash script to check if a domain or list of do...
1,https://github.com/windowjs/windowjs,windowjs,17,C++,Window.js is an open-source Javascript runtime...
2,https://github.com/withastro/astro,astro,453,TypeScript,"Build fast websites, faster. 🚀🧑‍🚀✨"
3,https://github.com/CyC2018/CS-Notes,CS-Notes,"46,146",Java,📚 技术面试必备基础知识、Leetcode、计算机操作系统、计算机网络、系统设计
4,https://github.com/apache/superset,superset,"8,437",TypeScript,Apache Superset is a Data Visualization and Da...
5,https://github.com/eugeneyan/applied-ml,applied-ml,"2,553",-,📚 Papers & tech blogs by companies sharing the...
6,https://github.com/cyrildiagne/ar-cutpaste,ar-cutpaste,"1,979",TypeScript,Cut and paste your surroundings using AR
7,https://github.com/abigsoft/jdog202201,jdog202201,117,C#,京东2022炸年兽
8,https://github.com/sottlmarek/DevSecOps,DevSecOps,211,-,Ultimate DevSecOps library
9,https://github.com/facebookresearch/ConvNeXt,ConvNeXt,106,Python,Code release for ConvNeXt model
10,https://github.com/input-output-hk/plutus-apps,plutus-apps,74,Haskell,The Plutus application platform
11,https://github.com/crater-invoice/crater,crater,"1,002",PHP,Open Source Invoicing Solution for Individuals...
12,https://github.com/MoienTajik/AspNetCore-Devel...,AspNetCore-Developer-Roadmap,"1,382",-,Roadmap to becoming an ASP.NET Core developer ...
13,https://github.com/windowtoolbox/powershell-wi...,powershell-windows-toolbox,99,-,⛽️「算法通关手册」，超详细的「算法与数据结构」基础讲解教程，「LeetCode」650+ ...
14,https://github.com/commit-live-students/Data_S...,Data_Science_Masters_Program_2021,101,Jupyter Notebook,"Mastering Ethereum, by Andreas M. Antonopoulos..."
15,https://github.com/itcharge/LeetCode-Py,LeetCode-Py,76,Python,"Examples of how to create colorful, annotated ..."
16,https://github.com/ethereumbook/ethereumbook,ethereumbook,"3,150",JavaScript,LevelDB is a fast key-value storage library wr...
17,https://github.com/synercys/annotated_latex_eq...,annotated_latex_equations,88,TeX,YOLOv5 🚀 in PyTorch > ONNX > CoreML > TFLite
18,https://github.com/google/leveldb,leveldb,"6,196",C++,A modern file manager that pushes the boundari...
19,https://github.com/ultralytics/yolov5,yolov5,"7,409",Python,The all-in-one tool to supercharge your produc...
20,https://github.com/input-output-hk/plutus-pion...,plutus-pioneer-program,486,Haskell,浙江大学课程攻略共享计划
21,https://github.com/files-community/Files,Files,929,C#,Zinc Search engine. A lightweight alternative ...

Q6Scrape the details of top 100 songs on billiboard.com.

Url = https:/www.billboard.com/

You have to find the following details: A) Song name B) Artist name C) Last week rank D) Peak rank E) Weeks on board Note: - From the home page you have to click on the charts option then hot 100-page link through code

In [43]:
# loading Chrome webdriver
driver = webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/2288193282.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")

In [44]:
# webpage opening
driver.get("https:/www.billboard.com/")
time.sleep(10)
# clicking the chart check box
loc=driver.find_element_by_xpath("//li[@class='o-nav__list-item ']/a")

# clicking the check box
loc.click()

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/2110749013.py:5: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  loc=driver.find_element_by_xpath("//li[@class='o-nav__list-item ']/a")

In [56]:
# Creating empty list for required data from the webpage.

bill={}
bill['SongName']=[]
bill['ArtistName']=[]
bill['Lastweek']=[]
bill['Peak']=[]
bill['Wksonchart']=[]

# extracting Song Name by xpath

try:
    for i in driver.find_elements_by_xpath('//h3[@class="c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only"]'):
            bill['SongName'].append(i.text)
except NoSuchElementExceptions:
    bill['SongName'].append('--')
        
# extracting Artist Name by xpath

try:
    for i in driver.find_elements_by_xpath('//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li/span'):
        bill['ArtistName'].append(i.text)
except NoSuchElementExceptions:
    bill['ArtistName'].append('--')
    
# extracting Last Week Rank by xpath

try:
    for i in driver.find_elements_by_xpath('//span[@class="c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max"]'):
        bill['Lastweek'].append(i.text)
except NoSuchElementExceptions:
    bill['Lastweek'].append('--')
    
# extracting Peak Rank by xpath

try:
    for i in driver.find_elements_by_xpath('//span[@class="c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max"]'):
        bill['Peak'].append(i.text)
except NoSuchElementExceptions:
    bill['Peak'].append('--')
    
# extracting Wks on Chart by xpath

try:
    for i in driver.find_elements_by_xpath('//span[@class="c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max"]'):
        bill['Wksonchart'].append(i.text)
except NoSuchElementExceptions:
    bill['Wksonchart'].append('--')

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1074342909.py:13: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath('//h3[@class="c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only"]'):
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1074342909.py:21: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath('//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li/span'):
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1074342909.py:29: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath('//span[@class="c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max"]'):
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1074342909.py:37: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath('//span[@class="c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max"]'):
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/1074342909.py:45: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath('//span[@class="c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max"]'):

In [57]:
print(len(bill['SongName']),len(bill['ArtistName']),len(bill['Lastweek']),len(bill['Peak']),len(bill['Wksonchart']))

99 400 594 594 594

In [58]:
#creating a dataframe
df=pd.DataFrame({'song':bill['SongName'][0:99],
                'artst':bill['ArtistName'][0:99],
                'weekrank':bill['Lastweek'][0:99],
                 'peak':bill['Peak'][0:99],
                'weekonboard':bill['Wksonchart'][0:99]})
df

,song,artst,weekrank,peak,weekonboard
0,Stay,Adele,6,6,6
1,Heat Waves,2,1,1,1
2,Shivers,1,26,26,26
3,We Don't Talk About Bruno,13,,,
4,Industry Baby,The Kid LAROI & Justin Bieber,,,
...,...,...,...,...,...
94,Me Or Sum,5,,,
95,I Love You So,7,,,
96,Bad Man (Smooth Criminal),Doja Cat & The Weeknd,-,-,-
97,Never Wanted To Be That Girl,42,1,1,1
98,Just About Over You,11,53,53,53

Q2 Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/.
You need to find following details: A) Match title (I.e. 1 st ODI) B) Series C) Place D) Date E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [68]:
# Importing selenium webdriver
from selenium import webdriver
# Connecting to the webdriver
driver=webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe") 
# Getting the webpage of mentioned url 
url=('https://www.bcci.tv/')
driver.get(url)

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/807595022.py:4: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")

In [69]:
Match_title=[]
Series=[]
Place=[]
Date=[]
Time_Note=[]

In [72]:
# Clicking on fixture button.
fixture=driver.find_element_by_xpath("//ul[@class='foot-list mb-5']//li[2]//a").click()

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/3772037587.py:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  fixture=driver.find_element_by_xpath("//ul[@class='foot-list mb-5']//li[2]//a").click()

In [86]:
#Creating empty lists to store scrape data.

fixtures={}
fixtures['Match_title']=[]
fixtures['Series']=[]
fixtures['Place']=[]
fixtures['Date']=[]
fixtures['Time']=[]

#extracting Match title

try:
    for i in driver.find_elements_by_xpath('//div[@class="fix-place ng-binding ng-scope"]'):
        fixtures['Match_title'].append(i.text)
except NoSuchElementExceptions:
    fixtures['Match_title'].append('--')
    
#extracting Series

try:
    for i in driver.find_elements_by_xpath('//div[@class="fixture-card-top"]/h5[2]/span'):
        fixtures['Series'].append(i.text)
except NoSuchElementExceptions:
    fixtures['Series'].append('--')
    
#extracting Place

try:
    for i in driver.find_elements_by_xpath('//div[@class="fix-place ng-binding ng-scope"]/span'):
        fixtures['Place'].append(i.text)
except NoSuchElementExceptions:
    fixtures['Place'].append('--')
    
#extracting Date and time 

try:
    for i in driver.find_elements_by_xpath('//h5[@class="ng-binding"]'):
        fixtures['Date'].append(i.text)
except NoSuchElementException:
    fixtures['Date'].append('--')
    
try:
    for i in driver.find_elements_by_xpath('//h5[@class="text-right ng-binding"]'):
        fixtures['Time'].append(i.text)
except NoSuchElementException:
    fixtures['Time'].append('--')

C:\Users\hp\AppData\Local\Temp/ipykernel_11120/200280130.py:13: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath('//div[@class="fix-place ng-binding ng-scope"]'):
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/200280130.py:21: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath('//div[@class="fixture-card-top"]/h5[2]/span'):
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/200280130.py:29: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath('//div[@class="fix-place ng-binding ng-scope"]/span'):
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/200280130.py:37: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath('//h5[@class="ng-binding"]'):
C:\Users\hp\AppData\Local\Temp/ipykernel_11120/200280130.py:43: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath('//h5[@class="text-right ng-binding"]'):

In [88]:
fixture=pd.DataFrame.from_dict(fixtures)
fixture

,Match_title,Series,Place,Date,Time
0,"- Providence Stadium, Guyana",ICC MENS UNDER 19 WORLD CUP 2022,"Providence Stadium,",15 JAN 2022,7:30 PM IST
1,"- Brian Lara Stadium, Trinidad",ICC MENS UNDER 19 WORLD CUP 2022,"Brian Lara Stadium,",19 JAN 2022,7:30 PM IST
2,"1st ODI - Boland Park, Paarl",INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"Boland Park,",19 JAN 2022,2:00 PM IST
3,"2nd ODI - Boland Park, Paarl",INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"Boland Park,",21 JAN 2022,2:00 PM IST
4,"- Brian Lara Stadium, Trinidad",ICC MENS UNDER 19 WORLD CUP 2022,"Brian Lara Stadium,",22 JAN 2022,7:30 PM IST
5,"3rd ODI - Newlands, Cape Town",INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"Newlands,",23 JAN 2022,2:00 PM IST
6,"1st ODI - NARENDRA MODI STADIUM, Ahmedabad",WEST INDIES TOUR OF INDIA ODI SERIES 2022,"NARENDRA MODI STADIUM,",6 FEB 2022,9:30 AM IST
7,"2nd ODI - Sawai Mansingh Stadium, Jaipur",WEST INDIES TOUR OF INDIA ODI SERIES 2022,"Sawai Mansingh Stadium,",9 FEB 2022,9:30 AM IST

In [89]:
driver.close()

Q3Scrape the details of selenium exception from guru99.com.

Url = https://www.guru99.com/

You need to find following details:

A) Name B) Description Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [9]:
# loading Chrome webdriver
driver = webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")
# opening url
driver.get('https://www.guru99.com/')
time.sleep(10)

C:\Users\hp\AppData\Local\Temp/ipykernel_15328/724308288.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/hp/Downloads/chromedriver.exe")

In [10]:
# Creating empty list
Name = []
Description = []

In [16]:
# entering “Selenium exception” in search field 
search_field=driver.find_element_by_id("gsc-i-id1")

search_field.send_keys("selenium exception handling")

C:\Users\hp\AppData\Local\Temp/ipykernel_15328/28243829.py:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_field=driver.find_element_by_id("gsc-i-id1")

In [17]:
# clicking the search button
search_button=driver.find_element_by_xpath("//button[@class='gsc-search-button gsc-search-button-v2']")
search_button.click

C:\Users\hp\AppData\Local\Temp/ipykernel_15328/1694064243.py:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_button=driver.find_element_by_xpath("//button[@class='gsc-search-button gsc-search-button-v2']")

In [46]:
# Clicking on fixture button.
sel=driver.find_element_by_xpath("//a[@class='gs-title']").click()

C:\Users\hp\AppData\Local\Temp/ipykernel_15328/2974768863.py:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  sel=driver.find_element_by_xpath("//a[@class='gs-title']").click()

In [41]:
for i in range(2,43):

    try:
        Name.append(driver.find_element_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]".format(i)).text)
    except NoSuchElementException:
        Name.append('--')
        
    try:
        Description.append(driver.find_element_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]".format(i)).text)
    except NoSuchElementException:
        Description.append('--')

C:\Users\hp\AppData\Local\Temp/ipykernel_15328/1955681230.py:4: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Name.append(driver.find_element_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]".format(i)).text)
C:\Users\hp\AppData\Local\Temp/ipykernel_15328/1955681230.py:9: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Description.append(driver.find_element_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]".format(i)).text)

In [44]:
selenium_exception = pd.DataFrame({ 'Name':Name[0:246],'Description': Description})
selenium_exception
# print(len(Name),len(Description))

    Name Description
0     --          --
1     --          --
2     --          --
3     --          --
4     --          --
..   ...         ...
241   --          --
242   --          --
243   --          --
244   --          --
245   --          --

[246 rows x 2 columns]